# Build workflow for Gtk LLM Chat
name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo add-apt-repository -y ppa:kubuntu-ppa/backports-extra
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build git \
            libxft-dev libepoxy-dev libgles2-mesa-dev libegl1-mesa-dev \
            libpolkit-agent-1-dev libpolkit-gobject-1-dev libunwind-dev \
            libx11-dev libxext-dev libdrm-dev libcups2-dev libsass-dev \
            linux-headers-$(uname -r) libcurl4-nss-dev libxcursor-dev \
            libxkbcommon-dev libxml2-utils libxrandr-dev libxi-dev \
            libwayland-dev libxinerama-dev \
            gperf libappstream-dev libxmlb-dev libxdamage-dev gettext valac \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            gir1.2-gtk-3.0 \
            gir1.2-ayatanaappindicator3-0.1 \
            libglib2.0-0 \
            libgirepository-1.0-1 \
            libdbus-1-dev \
            libdbus-glib-1-dev \
            gir1.2-dbusmenu-glib-0.4 \
            gir1.2-dbusmenu-gtk3-0.4 \
            gir1.2-glib-2.0

          sudo pip install --upgrade pip meson

      - name: Compila Gtk and friends
        run: |
          echo "Compiling gobject-introspection into /usr"
          echo "Using PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          GOBJECT_INTROSPECTION_VERSION="1.80.0"
          wget "https://download.gnome.org/sources/gobject-introspection/${GOBJECT_INTROSPECTION_VERSION%.*}/gobject-introspection-${GOBJECT_INTROSPECTION_VERSION}.tar.xz"
          tar -xf "gobject-introspection-${GOBJECT_INTROSPECTION_VERSION}.tar.xz"
          cd "gobject-introspection-${GOBJECT_INTROSPECTION_VERSION}"
          meson setup _build --prefix=/usr \
            --buildtype=release \
            -Ddoctool=disabled
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          git clone https://gitlab.gnome.org/GNOME/glib.git --branch glib-2-82 --depth 1
          cd glib
          meson setup _build --prefix=/usr \
            -Dintrospection=enabled \
            --buildtype=release -Ddocumentation=false -Dtests=false -Dman=false
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          git clone https://gitlab.gnome.org/GNOME/pango.git --branch 1.52.2 --depth 1
          cd pango
          meson setup _build --prefix=/usr \
            --buildtype=release -Dintrospection=enabled \
            -Dfontconfig=enabled -Dfreetype=enabled
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          wget "https://download.gnome.org/sources/graphene/1.8/graphene-1.8.6.tar.xz"
          tar -xf "graphene-1.8.6.tar.xz"
          cd "graphene-1.8.6"
          meson setup _build --prefix=/usr \
            --buildtype=release \
            -Dtests=false
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          git clone https://gitlab.freedesktop.org/fontconfig/fontconfig.git --branch 2.15.0 --depth 1
          cd fontconfig
          meson setup _build --prefix=/usr \
            --buildtype=release -Ddoc=disabled -Dtests=disabled -Dtools=disabled
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          git clone https://gitlab.gnome.org/GNOME/gtk.git --branch gtk-4-18 --depth 1
          cd gtk
          meson setup _build --prefix=/usr \
            --buildtype=release \
            -Dmedia-gstreamer=disabled \
            -Dbuild-tests=false \
            -Dbuild-examples=false \
            -Dbuild-demos=false \
            -Dintrospection=enabled \
            -Dvulkan=disabled
          ninja -C _build
          sudo ninja -C _build install
          cd ..
          git clone https://gitlab.gnome.org/GNOME/libadwaita.git --branch libadwaita-1-7 --depth 1
          cd libadwaita
          meson setup _build --prefix=/usr \
            -Dintrospection=enabled \
            --buildtype=release
          ninja -C _build
          sudo ninja -C _build install

      - name: Set environment for build
        run: |
          cp .env.ci .env

      - name: Build package
        run: |
          python3 build-ci.py

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: dist/

  build-windows:
    name: Build for Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install dependencies
        run: |
          ./windows/bootstrap.sh

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Set up environment
        run: |
          cp .env.ci .env

      - name: Build package
        run: |
          python3 build-ci.py

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/

  build-python:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build

      - name: Build Python package
        run: |
          python3 -m build

      - name: Store Python dist
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/
